/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			colors: {
				error: "#ba1a1a",
				"surface-container-high": "#d9eafc",
				"on-primary": "#ffffff",
				"tertiary-fixed": "#93f2f2",
				"on-primary-fixed-variant": "#76320f",
				"primary-fixed-dim": "#ffb596",
				"surface-container-low": "#ecf4ff",
				"surface-container-highest": "#d4e4f6",
				"on-surface": "#0d1d2a",
				"on-secondary": "#ffffff",
				"tertiary-container": "#007474",
				"surface-bright": "#f7f9ff",
				"on-primary-container": "#ffe1d6",
				"surface-tint": "#944925",
				"on-primary-fixed": "#360f00",
				"inverse-surface": "#223240",
				"on-secondary-fixed-variant": "#574500",
				tertiary: "#005959",
				"secondary-fixed-dim": "#e9c349",
				"surface-variant": "#d4e4f6",
				"on-background": "#0d1d2a",
				primary: "#823b18",
				"on-surface-variant": "#54433c",
				"on-secondary-fixed": "#241a00",
				"outline-variant": "#dac1b8",
				"tertiary-fixed-dim": "#76d6d5",
				"on-tertiary-fixed-variant": "#004f4f",
				"on-secondary-container": "#745c00",
				"secondary-container": "#fed65b",
				secondary: "#735c00",
				"on-tertiary": "#ffffff",
				"on-error": "#ffffff",
				"secondary-fixed": "#ffe088",
				outline: "#87736b",
				"on-tertiary-container": "#98f8f7",
				"inverse-primary": "#ffb596",
				"primary-container": "#a0522d",
				"on-error-container": "#93000a",
				"surface-container-lowest": "#ffffff",
				"surface-dim": "#cbdcee",
				"error-container": "#ffdad6",
				surface: "#f7f9ff",
				"primary-fixed": "#ffdbcd",
				"on-tertiary-fixed": "#002020",
				"inverse-on-surface": "#e7f2ff",
				"surface-container": "#e2efff",
				background: "#f7f9ff",
			},
			fontFamily: {
				headline: ["Noto Serif", "serif"],
				body: ["Manrope", "sans-serif"],
				label: ["Manrope", "sans-serif"],
				serif: ["Noto Serif", "serif"],
				sans: ["Manrope", "sans-serif"],
			},
			borderRadius: {
				DEFAULT: "0.25rem",
				sm: "0.25rem",
				lg: "0.5rem",
				xl: "0.75rem",
				full: "9999px",
			},
			spacing: {
				0: "0",
				1: "0.25rem",
				2: "0.5rem",
				3: "0.75rem",
				4: "1rem",
				5: "1.25rem",
				6: "1.5rem",
				8: "2rem",
				10: "2.5rem",
				12: "3rem",
				16: "4rem",
				20: "5rem",
			},
			boxShadow: {
				"artifact-shadow": "0px 20px 40px rgba(13, 29, 42, 0.05)",
			},
		},
	},
	plugins: [],
};
